spring:
  application:
  name: usercenter
  datasource:
    url: jdbc:mysql://localhost:3306/user_center
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver


server:
  port: 8080
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false

